FROM welasco/cusbase

COPY DotNetCoreAspNet/bin/Debug/netcoreapp2.2/publish /DotNetCoreAspNet

USER root

RUN cd /DotNetCoreAspNet \
   && chown -R dotnet:dotnet .\
   && chmod 644 *

USER dotnet

ENTRYPOINT ["/bin/init_container.sh"]