FROM welasco/cusbase

COPY Angular/bin/Debug/netcoreapp2.2/publish /Angular

USER root

RUN cd /Angular \
   && chown -R dotnet:dotnet .

COPY init_container.sh /bin/
RUN chmod 755 /bin/init_container.sh

ENV PORT 8080
ENV SSH_PORT 2222
EXPOSE 8080 2222

USER dotnet

ENTRYPOINT ["/bin/init_container.sh"]